# Generated by Django 3.2.3 on 2021-07-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0004_remove_bankdetail_ifsc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='ifsc_code',
            field=models.CharField(default='BKID', max_length=255),
        ),
    ]
