# Generated by Django 3.2.3 on 2021-07-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0006_alter_bankdetail_ifsc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='gst_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
