# Generated by Django 3.2.3 on 2021-11-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('blog', 'Blog'), ('news_letter', 'News Letter'), ('seminar', 'Seminar')], max_length=12)),
                ('content', models.TextField()),
            ],
        ),
    ]
