# Generated by Django 3.2.3 on 2021-06-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_artist_firm_interior_decorator'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interior_decorator',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
