# Generated by Django 3.2.3 on 2021-06-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
