# Generated by Django 3.2.3 on 2021-06-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210604_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomPasswords',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('random_string', models.CharField(max_length=36)),
            ],
        ),
    ]
