# Generated by Django 3.2.3 on 2021-06-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_randompasswords_randompassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.firm'),
        ),
        migrations.AlterField(
            model_name='interior_decorator',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.firm'),
        ),
    ]
