# Generated by Django 3.2.3 on 2021-06-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210615_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='followers',
            field=models.ManyToManyField(blank=True, to='users.Interior_Decorator'),
        ),
    ]
