# Generated by Django 3.2.3 on 2021-06-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_artist_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='firm',
        ),
    ]
