# Generated by Django 3.2.3 on 2021-07-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_personal_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='personal_address',
            field=models.CharField(max_length=256),
        ),
    ]
