# Generated by Django 3.2.3 on 2021-07-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_personal_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='personal_address',
        ),
    ]
