# Generated by Django 3.2.3 on 2021-09-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210821_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Unique_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
