# Generated by Django 3.2.3 on 2021-08-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='slug',
            field=models.CharField(default='name', max_length=250),
            preserve_default=False,
        ),
    ]
