# Generated by Django 3.2.3 on 2021-08-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_reviews_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='design',
            new_name='colorway',
        ),
    ]
