# Generated by Django 3.2.3 on 2021-08-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0009_designtag_designs_des_name_fa1665_idx'),
        ('product', '0010_rename_design_product_colorway'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='designs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='designs.design'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='colorway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.colorway'),
        ),
    ]
