# Generated by Django 3.2.3 on 2021-08-20 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210821_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='designs',
            new_name='design',
        ),
    ]
