# Generated by Django 3.2.3 on 2021-08-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_designs_product_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
