# Generated by Django 3.2.3 on 2021-08-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_tag',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
