# Generated by Django 3.2.3 on 2021-11-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='product',
            new_name='products',
        ),
    ]
