# Generated by Django 3.2.3 on 2021-06-18 15:02

import designs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designs', '0002_auto_20210615_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_customizable', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applications', models.ManyToManyField(to='product.Application')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesignTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='design',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='design',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='design',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='design',
            name='is_customizable',
        ),
        migrations.RemoveField(
            model_name='design',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='design',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='design',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='design',
            name='products',
        ),
        migrations.RemoveField(
            model_name='design',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='design',
            name='user',
        ),
        migrations.AddField(
            model_name='design',
            name='image',
            field=models.ImageField(default='', upload_to=designs.models.image_upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='saved_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DesignImage',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=models.ManyToManyField(to='designs.DesignTag'),
        ),
        migrations.AddField(
            model_name='design',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='designs.collection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='color_tag',
            field=models.ForeignKey(limit_choices_to={'label': 'Color'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='designs.designtag'),
        ),
    ]
