# Generated by Django 3.2.3 on 2021-06-25 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designs', '0005_alter_design_saved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colorway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image_url', models.URLField()),
                ('color_tags', models.ManyToManyField(limit_choices_to={'label': 'Color'}, to='designs.DesignTag')),
            ],
        ),
        migrations.RemoveField(
            model_name='design',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='design',
            name='color_tag',
        ),
        migrations.RemoveField(
            model_name='design',
            name='image',
        ),
        migrations.RemoveField(
            model_name='design',
            name='saved_by',
        ),
        migrations.RemoveField(
            model_name='design',
            name='views',
        ),
        migrations.AddField(
            model_name='design',
            name='applications',
            field=models.ManyToManyField(to='product.Application'),
        ),
        migrations.AddField(
            model_name='design',
            name='artist',
            field=models.ForeignKey(default=1, limit_choices_to={'type': [1, 2]}, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='design',
            name='is_customizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='design',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='design',
            name='tags',
            field=models.ManyToManyField(to='designs.DesignTag'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.AddField(
            model_name='colorway',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.design'),
        ),
        migrations.AddField(
            model_name='colorway',
            name='favourited_by',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 2}, to=settings.AUTH_USER_MODEL),
        ),
    ]
