# Generated by Django 3.2.3 on 2021-06-25 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designs', '0006_auto_20210625_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='artist',
            field=models.ForeignKey(limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
