# Generated by Django 3.2.3 on 2021-07-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0008_alter_design_artist'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='designtag',
            index=models.Index(fields=['name'], name='designs_des_name_fa1665_idx'),
        ),
    ]
