# Generated by Django 3.2.3 on 2021-08-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0010_design_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['slug'], name='designs_des_slug_74d3bd_idx'),
        ),
    ]
