# Generated by Django 3.2.3 on 2021-11-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_rename_product_collection_products'),
        ('designs', '0012_remove_colorway_favourited_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('remarks', models.TextField()),
                ('image', models.ImageField(upload_to='custom_designs/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.application')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
