# Generated by Django 3.2.3 on 2021-11-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0014_uploadowndesign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customization',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='customization',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='custom_designs/'),
        ),
        migrations.AddField(
            model_name='customization',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='custom_designs/'),
        ),
        migrations.AddField(
            model_name='customization',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='custom_designs/'),
        ),
    ]
