# Generated by Django 3.2.3 on 2021-11-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0015_auto_20211125_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='unit',
            field=models.CharField(default='cm', max_length=4),
            preserve_default=False,
        ),
    ]
