# Generated by Django 3.2.3 on 2021-06-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Entry Level'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')], max_length=12)),
                ('start_point', models.IntegerField()),
                ('end_point', models.IntegerField()),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoyaltyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Entry Level'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')], max_length=12)),
                ('start_point', models.IntegerField()),
                ('end_point', models.IntegerField()),
                ('royalty_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
