# Generated by Django 3.2.3 on 2021-06-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissiongroup',
            name='name',
            field=models.IntegerField(choices=[(1, 'Entry Level'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')]),
        ),
        migrations.AlterField(
            model_name='royaltygroup',
            name='name',
            field=models.IntegerField(choices=[(1, 'Entry Level'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')]),
        ),
    ]
