# Generated by Django 3.2.3 on 2021-11-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderstatus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('line1', models.TextField()),
                ('line2', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('pincode', models.IntegerField()),
                ('date', models.DateField()),
                ('timeframe_of_measurement', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('site_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
