# Generated by Django 3.2.3 on 2021-11-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_measurementrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementrequest',
            name='site_image',
        ),
        migrations.AddField(
            model_name='measurementrequest',
            name='site_image1',
            field=models.ImageField(default='asa', upload_to='site_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementrequest',
            name='site_image2',
            field=models.ImageField(blank=True, null=True, upload_to='site_image/'),
        ),
        migrations.AddField(
            model_name='measurementrequest',
            name='site_image3',
            field=models.ImageField(blank=True, null=True, upload_to='site_image/'),
        ),
        migrations.AddField(
            model_name='measurementrequest',
            name='site_image4',
            field=models.ImageField(blank=True, null=True, upload_to='site_image/'),
        ),
    ]
