# Generated by Django 3.2.3 on 2021-06-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_remove_artist_firm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_frequency', models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
                ('payment_frequency', models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
                ('design_view_frequency', models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
                ('design_purchase_frequency', models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.artist')),
            ],
            options={
                'verbose_name_plural': 'Notification settings',
            },
        ),
    ]
