# Generated by Django 3.2.3 on 2021-07-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_artistnotificationsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistnotificationsettings',
            name='design_favorite_frequency',
            field=models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1),
        ),
    ]
